name: Deploy metadata to prod

on:
  push:
    branches:
      - master

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      HASURA_GRAPHQL_ADMIN_SECRET: Dc0ftxq7sXnG9DfbqABY4dSyHGPb1lRTgGOWlFlNq4C9zoLB5zK6tEmV28nCEog4
      HASURA_GRAPHQL_ENDPOINT: https://next-gannet-85.hasura.app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Hasura CLI
        uses: hasura/action@v1.4.1
        with:
          version: latest
          cli_path: /usr/local/bin/hasura
      - name: Apply migrations
        run: hasura migrate apply --endpoint ${{ env.HASURA_GRAPHQL_ENDPOINT }} --admin-secret ${{ env.HASURA_GRAPHQL_ADMIN_SECRET }}
      - name: Apply metadata
        run: hasura metadata apply --endpoint ${{ env.HASURA_GRAPHQL_ENDPOINT }} --admin-secret ${{ env.HASURA_GRAPHQL_ADMIN_SECRET }}
      - name: Reload metadata
        run: hasura metadata reload --endpoint ${{ env.HASURA_GRAPHQL_ENDPOINT }} --admin-secret ${{ env.HASURA_GRAPHQL_ADMIN_SECRET }}
