name: deploy to cloud

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      HASURA_GRAPHQL_ADMIN_SECRET: Dc0ftxq7sXnG9DfbqABY4dSyHGPb1lRTgGOWlFlNq4C9zoLB5zK6tEmV28nCEog4
      HASURA_GRAPHQL_ENDPOINT: https://next-gannet-85.hasura.app
    steps:
      - name: Download Hasura CLI
        run: |
          curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
      - name: Verify Hasura CLI version
        run: |
          hasura version
      - name : list files
        run: |
          cd $GITHUB_WORKSPACE
          echo "Current working directory is $(pwd)"
          echo "Current working files is $(ls)"
      - name: Apply migrations
        run: |
          hasura migrate apply --endpoint ${{ env.HASURA_GRAPHQL_ENDPOINT }} --admin-secret ${{ env.HASURA_GRAPHQL_ADMIN_SECRET }} --database-name default
      - name: Apply metadata
        run: |
          hasura metadata apply --endpoint ${{ env.HASURA_GRAPHQL_ENDPOINT }} --admin-secret ${{ env.HASURA_GRAPHQL_ADMIN_SECRET }}
      - name: Reload metadata
        run: |
          hasura metadata reload --endpoint ${{ env.HASURA_GRAPHQL_ENDPOINT }} --admin-secret ${{ env.HASURA_GRAPHQL_ADMIN_SECRET }}
