name: deploy to cloud

on:
  pull_request:
    branches:
      - main

jobs:
  hasura-migrations:
    runs-on: ubuntu-latest
    env:
      HASURA_GRAPHQL_ADMIN_SECRET: Dc0ftxq7sXnG9DfbqABY4dSyHGPb1lRTgGOWlFlNq4C9zoLB5zK6tEmV28nCEog4
      HASURA_GRAPHQL_ENDPOINT: https://next-gannet-85.hasura.app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download Hasura CLI
        run: |
          curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
      - name: Verify Hasura CLI version
        run: |
          hasura version
      - name: Run hasura metadata diff
        run: |
          hasura metadata diff --endpoint ${{ env.HASURA_GRAPHQL_ENDPOINT }} --admin-secret ${{ env.HASURA_GRAPHQL_ADMIN_SECRET }}
      - name: Save metadata diff
        id: save-metadata-diff
        run: |
          echo ::set-output name=diff::$(hasura metadata diff --endpoint ${{ env.HASURA_GRAPHQL_ENDPOINT }} --admin-secret ${{ env.HASURA_GRAPHQL_ADMIN_SECRET }} --output-format json)
          timeout-minutes: 60
  deploy:
    runs-on: ubuntu-latest
    needs: manual-approval
    env:
      HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
      HASURA_GRAPHQL_ENDPOINT: https://next-gannet-85.hasura.app
    steps:
      - name: Apply migrations
        run: |
          hasura migrate apply --endpoint ${{ env.HASURA_GRAPHQL_ENDPOINT }} --admin-secret ${{ env.HASURA_GRAPHQL_ADMIN_SECRET }} --database-name default
      - name: Apply metadata
        run: |
          hasura metadata apply --endpoint ${{ env.HASURA_GRAPHQL_ENDPOINT }} --admin-secret ${{ env.HASURA_GRAPHQL_ADMIN_SECRET }} --metadata-file ${{ steps.save-metadata-diff.outputs.diff }}
      - name: Reload metadata
        run: |
          hasura metadata reload --endpoint ${{ env.HASURA_GRAPHQL_ENDPOINT }} --admin-secret ${{ env.HASURA_GRAPHQL_ADMIN_SECRET }}
